name: GenseDeathRespawnListener
main: jp.example.gense.GenseDeathRespawnListener
version: 1.0
api-version: 1.13
commands:
  jigoku:
    description: 地獄サーバーに移動します
    usage: /<command>
  adminjigoku:
    description: 管理者用 - 制限なく地獄サーバーに移動します
    usage: /<command>
    permission: gense.admin
  jigokutime:
    description: 地獄ワールドの現在時刻を確認します
    usage: /<command>
permissions:
  gense.admin:
    description: 管理者用コマンドの使用を許可します
    default: op
    default: op
