name: GenseDeathRespawnListener
main: jp.example.gense.GenseDeathRespawnListener
version: 1.0
api-version: 1.20
author: So4246la
description: 現世サーバーで地獄から死亡後リスポーンした際に擬似リスポーンイベントを発火する
depend: []
softdepend: []
commands:
  jigoku:
    description: 地獄サーバーへ移動します。
    usage: /jigoku
  adminjigoku:
    description: 管理者用 - 制限なく地獄サーバーへ移動します。
    usage: /adminjigoku
    permission: gense.admin
permissions:
  gense.admin:
    description: 管理者用コマンドの使用を許可します
    default: op
