spawn-range-min: 5000  # 最小距離（原点から離れた場所にスポーン）
spawn-range-max: 20000 # 最大距離

# MySQL設定
mysql:
  enabled: true
  host: localhost
  port: 3306
  database: jigoku_bancontrol
  username: root
  password: password
