name: JigokuBanControl
main: jp.example.jigokubancontrol.JigokuBanControlPlugin
version: 1.0
api-version: 1.13
softdepend:
  - HuskSync
commands:
  gense:
    description: 現世サーバーに移動します
    usage: /<command>
    permission: jigokubancontrol.gense
  admingense:
    description: 管理者用 - 制限なく現世サーバーに移動します
    usage: /<command>
    permission: jigokubancontrol.admin
  jigokutime:
    description: 地獄ワールドの現在時刻を確認します
    usage: /<command>
    permission: jigokubancontrol.time
permissions:
  jigokubancontrol.gense:
    description: 現世サーバーへの移動を許可します
    default: true
  jigokubancontrol.admin:
    description: 管理者用コマンドの使用を許可します
    default: op
  jigokubancontrol.time:
    description: 地獄の時刻確認を許可します
    default: true
  jigokuban.debug:
    description: デバッグ情報の表示を許可します
    default: op
